// $Id: JMacPanel.java,v 1.3 2007/06/14 12:57:07 jim Exp $

package us.temerity.plconfig;

import us.temerity.plconfig.ui.*;

import java.io.*;
import java.util.*;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

/*------------------------------------------------------------------------------------------*/
/*   M A C   P A N E L                                                                      */
/*------------------------------------------------------------------------------------------*/

/**
 * The Mac OS X paths.
 */ 
class JMacPanel
  extends JBaseConfigPanel
  implements ActionListener
{  
  /*----------------------------------------------------------------------------------------*/
  /*   C O N S T R U C T O R                                                                */
  /*----------------------------------------------------------------------------------------*/

  /** 
   * Construct a new panel.
   */ 
  public
  JMacPanel
  (
   ConfigApp app
  ) 
  {
    super(app, "Mac OS X Paths:");
    
    /* initialize UI components */ 
    {
      {
	Box hbox = new Box(BoxLayout.X_AXIS);

	{
	  Box vbox = new Box(BoxLayout.Y_AXIS);

	  vbox.add(UIFactory.createPanelLabel("Mac Support:")); 

	  vbox.add(Box.createRigidArea(new Dimension(0, 3)));
	  
	  {
	    pSupportField = UIFactory.createBooleanField(sHSize);
	    
	    pSupportField.addActionListener(this);
	    pSupportField.setActionCommand("support-changed");
	    
	    vbox.add(pSupportField); 
	  }

	  vbox.add(Box.createRigidArea(new Dimension(0, 20)));
	  
	  pRootDirComp = new JAbsoluteDirComp("Root Install Directory", sHSize, false);
	  vbox.add(pRootDirComp);
	  
	  vbox.add(Box.createRigidArea(new Dimension(0, 20)));
	  
	  pHomeDirComp = new JAbsoluteDirComp("Home Directory", sHSize, false);
	  vbox.add(pHomeDirComp);

	  hbox.add(vbox);
	}

	hbox.add(Box.createRigidArea(new Dimension(40, 0)));

	{
	  Box vbox = new Box(BoxLayout.Y_AXIS);

	  vbox.add(Box.createRigidArea(new Dimension(0, 60)));

	  pProdDirComp = new JAbsoluteDirComp("Production Directory", sHSize, false);
	  vbox.add(pProdDirComp);
	  
	  vbox.add(Box.createRigidArea(new Dimension(0, 20)));
	  
	  pTempDirComp = new JAbsoluteDirComp("Temporary Directory", sHSize, false);
	  vbox.add(pTempDirComp);

	  hbox.add(vbox);
	}

	add(hbox);
      }
        
      add(Box.createRigidArea(new Dimension(0, 40)));
      
      pJavadocDirComp = new JAbsoluteDirComp("Local Vendor Javadoc Directory", sSize, false);
      add(pJavadocDirComp);
      
      add(Box.createRigidArea(new Dimension(0, 20)));
      
      pExtraJavaLibsComp = new JAbsoluteJarsComp("Local Java Libraries", sSize, false);
      add(pExtraJavaLibsComp);
      
      add(Box.createRigidArea(new Dimension(0, 20)));
      add(Box.createVerticalGlue());
    }
      
    pNotesDialog.setMessage
      ("Mac OS X Parameters:", 
       "If you will be using Pipeline on Mac OS X hosts, you need to enable the Mac OS " + 
       "X Support.  Due to differences between Linux and Darwin (Mac OS X) standard " + 
       "paths and in how network file systems are accessed, the paths required by " + 
       "Pipeline must be seperately configured for Mac OS X systems.\n" + 
       "\n" + 
       "The Root Install Directory and Production Directory should map to the same " + 
       "network file system directories seen from Mac OS X systems as the corresponing " + 
       "Linux paths specified earlier. For example, a Linux path such as " + 
       "(/base/prod) might might be mapped to something like " + 
       "(/Network/Servers/myserver/base/prod) on a Mac OS X system.\n" + 
       "\n" + 
       "The Home Directory is not required to be shared between Linux and Mac OS X " +
       "systems and might even reside on a local file system.   The Temporary Directory " + 
       "should reside on a local file system for optimal performance.\n" +
       "\n" + 
       "The Local Vendor Javadoc Directory is the path to the root directory where the " + 
       "documentation generated by javadoc for locally created Pipeline plugins and " + 
       "standalone utils is located.  Providing this will allow users to easily access " +
       "the documentation for locally created plugins from Pipeline's user interface.\n" +
       "\n" + 
       "The Local Java Libraries is a optional set of JAR files containing common Java " + 
       "class shared by a large number of locally created plugins and/or standalone " + 
       "utils.  Any JARs provided will be added to the Java classpath for all Pipeline " + 
       "programs.  This is typically used for relatively large 3rd party libraries for " + 
       "things such as XML parsing or SQL database connections which would otherwise " + 
       "need to be embedded in many different plugin JARs.  Since these libraries " + 
       "be dynamically updated (like plugins can), they are not suitable for anything " + 
       "which might need to modified without a Pipeline shutdown.  This feature is " + 
       "only an optimization to reduce plugin size and memory footprint but is not " + 
       "required in order to use 3rd party Java libraries with Pipeline."); 
  }


  /*----------------------------------------------------------------------------------------*/
  /*   P A N E L   O P S                                                                    */
  /*----------------------------------------------------------------------------------------*/
  
  /**
   * The unique name of the panel.
   */ 
  public String
  getPanelTitle()
  {
    return "Mac OS X";
  }

  /**
   * Initialize the panel UI component values from the current site profile settings.
   */ 
  public void 
  updatePanel() 
  { 
    pSupportField.setValue(pApp.getMacSupport());
    doSupportChanged();
  }
  
  /**
   * Validate the current UI values and update the site profile settings.
   * 
   * @throws IllegalConfigException
   *   If the current UI values are invalid.
   */ 
  public void 
  updateProfile() 
    throws IllegalConfigException
  {
    boolean enabled = pSupportField.getValue(); 
    pApp.setMacSupport(enabled);
    if(enabled) {
      pApp.setMacRootDirectory(pRootDirComp.validateDir(pApp)); 
      pApp.setMacProdDirectory(pProdDirComp.validateDir(pApp)); 
      pApp.setMacHomeDirectory(pHomeDirComp.validateDir(pApp)); 
      pApp.setMacTemporaryDirectory(pTempDirComp.validateDir(pApp)); 
      pApp.setMacLocalJavadocDirectory(pJavadocDirComp.validateDir(pApp));
      pApp.setMacLocalJavaLibraries(pExtraJavaLibsComp.validateJars(pApp));
    }
  }



  /*----------------------------------------------------------------------------------------*/
  /*   L I S T E N E R S                                                                    */
  /*----------------------------------------------------------------------------------------*/

  /*-- ACTION LISTENER METHODS -------------------------------------------------------------*/

  /** 
   * Invoked when an action occurs. 
   */ 
  public void 
  actionPerformed
  (
   ActionEvent e
  ) 
  {
    super.actionPerformed(e); 

    String cmd = e.getActionCommand();
    if(cmd.equals("support-changed")) 
      doSupportChanged();
  }



  /*----------------------------------------------------------------------------------------*/
  /*   A C T I O N S                                                                        */
  /*----------------------------------------------------------------------------------------*/

  private void
  doSupportChanged() 
  {
    boolean enabled = pSupportField.getValue(); 
    
    pRootDirComp.setEnabled(enabled);
    pProdDirComp.setEnabled(enabled);
    pHomeDirComp.setEnabled(enabled);
    pTempDirComp.setEnabled(enabled);
    pJavadocDirComp.setEnabled(enabled);
    pExtraJavaLibsComp.setEnabled(enabled);
    
    if(!enabled)
      return; 

    {
      File dir = pApp.getMacRootDirectory();
      if(dir == null) 
	dir = new File("/Network/Servers/myserver" + pApp.getRootDirectory());
      pRootDirComp.setDir(dir);
    }
    
    {
      File dir = pApp.getMacProdDirectory();
      if(dir == null) 
	dir = new File("/Network/Servers/myserver" + pApp.getProdDirectory());
      pProdDirComp.setDir(dir);	  
    }
    
    {
      File dir = pApp.getMacHomeDirectory();
      if(dir == null) 
	dir = new File("/Users");
      pHomeDirComp.setDir(dir);
    }
	
    {
      File dir = pApp.getMacTemporaryDirectory();
      if(dir == null) 
	dir = new File("/var/tmp");
      pTempDirComp.setDir(dir);
    }

    pJavadocDirComp.setDir(pApp.getMacLocalJavadocDirectory());
    pExtraJavaLibsComp.setJars(pApp.getMacLocalJavaLibraries()); 
  }


  /*----------------------------------------------------------------------------------------*/
  /*   S T A T I C   I N T E R N A L S                                                      */
  /*----------------------------------------------------------------------------------------*/

  private static final long serialVersionUID = -5057981793263078739L;
  


  /*----------------------------------------------------------------------------------------*/
  /*   I N T E R N A L S                                                                    */
  /*----------------------------------------------------------------------------------------*/
  
  /**
   * The Mac OS X fields. 
   */ 
  private JBooleanField     pSupportField; 
  private JAbsoluteDirComp  pRootDirComp; 
  private JAbsoluteDirComp  pProdDirComp; 
  private JAbsoluteDirComp  pHomeDirComp; 
  private JAbsoluteDirComp  pTempDirComp; 
  private JAbsoluteDirComp  pJavadocDirComp; 
  private JAbsoluteJarsComp pExtraJavaLibsComp;

}



